---
title: Priam | copenhagen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  jobs:
    title: jobs
    output: true
email: kennethlarsen@protonmail.com
description: News, media and AI
name: Priam
location: Copenhagen, DK
markdown: kramdown
